DEFINE TABLE {{ db_name }}.CORE.athlete_events (
  ID     STRING,
  NAME   STRING,
  SEX    STRING,
  AGE    FLOAT,
  HEIGHT FLOAT,
  WEIGHT FLOAT,
  TEAM   STRING,
  NOC    STRING,
  GAMES  STRING,
  YEAR   FLOAT,
  SEASON STRING,
  CITY   STRING,
  SPORT  STRING,
  EVENT  STRING,
  MEDAL  STRING
);
